function [fitresult, gof] = linearFit(turn_average_ROI, torque_average_ROI)
%CREATEFIT(TURN_AVERAGE_ROI,TORQUE_AVERAGE_ROI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: turn_average_ROI
%      Y Output: torque_average_ROI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jun-2024 22:20:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( turn_average_ROI, torque_average_ROI );

% Set up fittype and options.
ft = fittype( 'k*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.983052466469856 0.701098755900926];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 4 );
h = plot( fitresult, xData, yData );
legend( h, 'torque_average_ROI vs. turn_average_ROI', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'turn_average_ROI', 'Interpreter', 'none' );
ylabel( 'torque_average_ROI', 'Interpreter', 'none' );
grid on
hold on


