function [fitresult, gof] = Charvin_first_half_Fit(a_turn_ROI, a_ext_ROI)
%CREATEFIT(A_TURN_ROI,A_EXT_ROI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: a_turn_ROI
%      Y Output: a_ext_ROI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jul-2024 22:22:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( a_turn_ROI, a_ext_ROI );

% Set up fittype and options.
ft = fittype( 'sqrt(z0^2-4*x0*(sin(pi*x))^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [20000 1800];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%Plot fit with data.
figure;
h = plot( fitresult, xData, yData );
legend( h, 'Data', 'Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Ca', 'Interpreter', 'none' );
ylabel( 'Extension (nm)', 'Interpreter', 'none' );
grid on
hold on


