function [fitresult, gof] = ext_slope_Fit(turn_current_pos_ROI, ext_current_pos_ROI)
%CREATEFIT(TURN_CURRENT_POS_ROI,EXT_CURRENT_POS_ROI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: turn_current_pos_ROI
%      Y Output: ext_current_pos_ROI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2024 16:24:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( turn_current_pos_ROI, ext_current_pos_ROI );

% Set up fittype and options.
ft = fittype( 'k*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.890475679184438 0.73434108369597];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 20 );
h = plot( fitresult, xData, yData );
legend( h, 'ext_current_pos_ROI vs. turn_current_pos_ROI', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'turn_current_pos_ROI', 'Interpreter', 'none' );
ylabel( 'ext_current_pos_ROI', 'Interpreter', 'none' );
grid on
hold on


