function [fitresult, gof] = linear_Fit(turn_all_crop_ROI_center, torque_all_crop_ROI_center)
%CREATEFIT(TURN_ALL_CROP_ROI_CENTER,TORQUE_ALL_CROP_ROI_CENTER)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: turn_all_crop_ROI_center
%      Y Output: torque_all_crop_ROI_center
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jul-2024 20:31:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( turn_all_crop_ROI_center, torque_all_crop_ROI_center );

% Set up fittype and options.
ft = fittype( 'k*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.521135830804001 0.395515215668593];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'torque_all_crop_ROI_center vs. turn_all_crop_ROI_center', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'turn_all_crop_ROI_center', 'Interpreter', 'none' );
% ylabel( 'torque_all_crop_ROI_center', 'Interpreter', 'none' );
% grid on


