function [fitresult, gof] = buckling_transition_Fit_v2(a_turn_for_ext_ROI, a_ext_ROI)
%CREATEFIT(A_TURN_FOR_EXT_ROI,A_EXT_ROI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: a_turn_for_ext_ROI
%      Y Output: a_ext_ROI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Aug-2024 16:17:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( a_turn_for_ext_ROI, a_ext_ROI );

% Set up fittype and options.
ft = fittype( '(p1*x^2+p2*x+p3)*(x<xb)+(k*(x-xb)+p1*xb^2+p2*xb+p3)*(x>=xb)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf 0 0];
opts.StartPoint = [-40 -0.03 -1 1950 92];
opts.Upper = [Inf 0 0 Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure;
h = plot( fitresult, xData, yData );
legend( h, 'a_ext_ROI vs. a_turn_for_ext_ROI', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'a_turn_for_ext_ROI', 'Interpreter', 'none' );
ylabel( 'a_ext_ROI', 'Interpreter', 'none' );
grid on


